import { Component, OnInit } from '@angular/core';
import { TripService } from '../trip.service';
import { ActivatedRoute,Params } from '@angular/router';

@Component({
  selector: 'app-trips',
  templateUrl: './trips.component.html',
  styleUrls: ['./trips.component.css']
})
export class TripsComponent implements OnInit {
  trip_id:any;
  currentTrip={};
  newActivity={};
  newAgenda={};
  droppedSuggestions:any;
  droppedProposed:any;
  suggestions = [
    {location:"Suggestion 1",description:"Description for sug 1"},
    {location:"Suggestion 2",description:"Description for sug 2"},
    {location:"Suggestion 3",description:"Description for sug 3"},
    {location:"Suggestion 4",description:"Description for sug 4"},
    {location:"Suggestion 5",description:"Description for sug 5"},
    {location:"Suggestion 6",description:"Description for sug 6"}
  ];
  //code to keep
  agendas=[];
  currentAgenda={};
  //end code to keep
  constructor(
    private tripService:TripService,
    private route:ActivatedRoute
  ){}
  ngOnInit() {
    //get current trip info
    this.route.params.subscribe((params:Params)=>{
      this.trip_id=params['id'];
      this.tripService.findTripById(params['id']).subscribe(data=>{
        //make sure it exists
        if(data['title'] != null){
          this.currentTrip = data;      
          //set activities
          //set agendas   
          for(let i=0; i < this.currentTrip['agendas'].length; ++i){
            //each agenda may contain a list of activities that we
            //are adding to agendas(array of arrays)
            this.agendas.push(this.currentTrip['agendas'][i]);
          }
          //set current agenda to day one (this might need to be changed)
          this.currentAgenda = this.agendas[0];
          //this should be implemented when we create a new trip
        /*   if(this.currentTrip['agendas'].length == 0){
            this.newAgenda = {
              trip:this.currentTrip,
              day:1,
              date:Date.now()
            }
            this.tripService.createAgenda(this.newAgenda).subscribe(data=>{
              if(data['day'] != null) {
                 //this needs refactoring
                this.droppedProposed = this.currentTrip['agendas'][0]['activities'];
                console.log("successfully created agenda");
              }
              else console.log("error creating agenda");
            });
          }else{
             //this needs refactoring
             //this.droppedProposed = [];
             //this.droppedProposed = this.currentTrip['agendas'][0]['activities'];
          } */
        }else{
          console.log("there were errors while fetching trip");
        }
      });
    });
    //this needs to be changed: it is finding ALL activities suggestions
    //on the proposed section when we only need activities proposed only 
    //for this particular trip
    this.tripService.findAllActivities().subscribe(data=>{
      this.droppedSuggestions = data;
    });
  }
  //handles dropping a suggestion (generated by google api) into the 
  //proposed section
  onSuggestionDrop(e: any) {
    console.log("triggered");
    //data from google is not an activity yet, so we need to create one
    this.newActivity={
      description:e.dragData.description,
      location:e.dragData.location
    };
    /*******An activity should be associated with a trip?******/
    this.tripService.createActivity(this.newActivity).subscribe(data=>{
        //if succesfully created activity, added to our lists
        if(data['location'] != null){
          this.droppedSuggestions.push(data);
        } else{
          console.log("There are errors here")
        }
    });
  }
  //handles activities being dropped/moved into the agenda section
  onActivityDrop(e: any) {  
    //pass both ids(agenda and activity) and update on the many side
    this.tripService.addActivityToAgenda(e.dragData.id,this.currentAgenda['id']).subscribe(data=>{
        if(data['location'] != null){
          console.log("successfully added activity to agenda");
          //this.droppedProposed.push(data);
          this.currentAgenda['activities'].push(data);
        }else{
          console.log("errors adding act to agenda");
        }
    });
  }
  selectDay(day){
    console.log("clicked: "+day);
    this.currentAgenda = this.agendas[day-1];
  }
}
